version : "2"
services :
  mysql : 
    build : 
      context : ./mysql
      dockerfile : Dockerfile
    ports :
      - "3306:3306"
    volumes :
      - ./mysql/data:/var/lib/mysql
      - ./mysql/logs:/var/log/mysql
    environment : 
      - MYSQL_ROOT_PASSWORD=123456
    container_name : mysql
    restart : always
  php :
    build : 
      context : ./php
      dockerfile : Dockerfile
    ports :
      - "9000:9000"
    volumes :
      - ./www:/usr/share/nginx/html/
    container_name : php
    links : 
      - mysql
    restart : always
  nginx :
    build : 
      context : ./nginx
      dockerfile : Dockerfile
    ports : 
      - "80:80"
      - "443:443"
    volumes :
      - ./www:/usr/share/nginx/html/
      - ./nginx/logs:/var/log/nginx/
    container_name : nginx
    links : 
      - php
    restart : always
