version : "3"
services :
  mysql : 
    build : 
      context : ./mysql
      dockerfile : Dockerfile
    ports :
      - "3306:3306"
    volumes :
      - ./mysql/data:/var/lib/mysql
      - ./mysql/logs:/var/log/mysql
    environment : 
      - MYSQL_DATABASE=test
      - MYSQL_USER=test
      - MYSQL_PASSWORD=123456
      - MYSQL_ROOT_PASSWORD=123456
    container_name : mysql
    restart : always
    networks: 
      - lnmp
  php :
    build : 
      context : ./php
      dockerfile : Dockerfile
    ports :
      - "9000:9000"
    volumes :
      - ./www:/usr/share/nginx/html/
    container_name : php
    links : 
      - mysql
    restart : always
    networks: 
      - lnmp
  nginx :
    build : 
      context : ./nginx
      dockerfile : Dockerfile
    ports : 
      - "80:80"
      - "443:443"
      - "3002:3002"
    volumes :
      - ./www:/usr/share/nginx/html/
      - ./nginx/logs:/var/log/nginx/
    container_name : nginx
    links : 
      - php
    restart : always
    networks: 
      - lnmp
  redis : 
    build :
      context : ./redis
      dockerfile : Dockerfile
    ports :
      - "6379:6379"
    volumes :
      - ./redis/data:/data
    container_name : redis
    restart : always
    networks: 
      - lnmp
networks :
  lnmp : 
    driver : bridge
